# Numpy

## Arrays and Scalar

A scalar is an element of a field which is used to define a vector space. A quantity described by multiple scalars, such as having both direction and magnitude, is called a vector.

In linear algebra, real numbers or other elements of a field are called scalars and relate to vectors in a vector space through the operation of scalar multiplication, in which a vector can be multiplied by a number to produce another vector. <https://en.wikipedia.org/wiki/Scalar_(mathematics)>

In [11]:
# basic import
import numpy as np

In [12]:
# Create array
arr1 = np.array([[1,2,3],[8,9,10]])

#Show
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

#### Multiply 

In [14]:
#Multiplying Arrays
arr1 * arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

#### Subtract

In [15]:
#Subtraction
arr1 - arr1

array([[0, 0, 0],
       [0, 0, 0]])

#### Arithmetic

In [10]:
#Arithmetic operations with scalars on array
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.125     ,  0.11111111,  0.1       ]])

#### Esponential

In [16]:
#Exponential operation
arr1 ** 3

array([[   1,    8,   27],
       [ 512,  729, 1000]])

## Let's do some exercise!