# Numpy

## Basic Operations

In [1]:
# basic import
import numpy as np

In [5]:
# Create array
arr1 = np.array([[1,2,3],[8,9,10]])

arr2 = np.array([[10,20,30],[80,90,100]])

In [6]:
# Show
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [7]:
#Show
arr2

array([[ 10,  20,  30],
       [ 80,  90, 100]])

## Arithmetic

Arithmetic operators on arrays apply *elementwise*. A new array is created and filled with the result

#### Multiply 

In [9]:
#Multiplying Arrays
arr1 * arr2

array([[  10,   40,   90],
       [ 640,  810, 1000]])

#### Subtract

In [11]:
#Subtraction
arr2 - arr1

array([[ 9, 18, 27],
       [72, 81, 90]])

#### Division

In [12]:
#Arithmetic operations with scalars on array
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.125     , 0.11111111, 0.1       ]])

#### Esponential

In [13]:
#Exponential operation
arr1 ** 3

array([[   1,    8,   27],
       [ 512,  729, 1000]])

#### Comparison

In [14]:
# It returns a True False array
arr1 < 5

array([[ True,  True,  True],
       [False, False, False]])

## Sum, Min and Max of an Array

In [36]:
# create a new array
a = np.linspace(3, 33, 20)
a

array([ 3.        ,  4.57894737,  6.15789474,  7.73684211,  9.31578947,
       10.89473684, 12.47368421, 14.05263158, 15.63157895, 17.21052632,
       18.78947368, 20.36842105, 21.94736842, 23.52631579, 25.10526316,
       26.68421053, 28.26315789, 29.84210526, 31.42105263, 33.        ])

In [37]:
# sum
a.sum()

360.0

In [38]:
# min
a.min()

3.0

In [40]:
# max
a.max()

33.0

### Sum, Min, Max on axis

In [42]:
a.resize(5,4)
print(a)

[[ 3.          4.57894737  6.15789474  7.73684211]
 [ 9.31578947 10.89473684 12.47368421 14.05263158]
 [15.63157895 17.21052632 18.78947368 20.36842105]
 [21.94736842 23.52631579 25.10526316 26.68421053]
 [28.26315789 29.84210526 31.42105263 33.        ]]


Sum on rows

In [43]:
a.sum(axis=1)

array([ 21.47368421,  46.73684211,  72.        ,  97.26315789,
       122.52631579])

Sum on columns

In [44]:
a.sum(axis=0)

array([ 78.15789474,  86.05263158,  93.94736842, 101.84210526])

## Matrix product

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [27]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

In [28]:
# show array A
A

array([[1, 1],
       [0, 1]])

In [29]:
# show array B
B

array([[2, 0],
       [3, 4]])

In [30]:
# Multiplication
A * B

array([[2, 0],
       [0, 4]])

**Dot product**

In [32]:
# with the dot method
A.dot(B)

array([[5, 4],
       [3, 4]])

In [34]:
# with the @ operand
A @ B

array([[5, 4],
       [3, 4]])

## Let's do some exercise!