# Numpy

#### Documentation:

In [24]:
#For full documentation
website = "https://numpy.org/"
import webbrowser
webbrowser.open(website)

True

## Creatinng Arrays

In [1]:
# Creating Numpy arrays
import numpy as np

### 1-D Array from a list:

In [2]:
# Converting from a list
#Lets start with a list

my_list1 = [10,20,30,40]

my_array1 = np.array(my_list1)

In [3]:
#Print out array

my_array1

array([10, 20, 30, 40])

In [4]:
# Check my object
type(my_array1)

numpy.ndarray

In [5]:
# Checking the type of the array
my_array1.dtype

dtype('int32')

Change the type of the objects

In [8]:
new_array1 = np.array([10, 20, 30, 40], dtype='float')

new_array1

array([10., 20., 30., 40.])

In [9]:
new_array1.dtype

dtype('float64')

### 2-D array from a list

In [ ]:
# Make another list
my_list2 = [100,200,300,400]

#Make a list of lists
multy_lists = [my_list1, my_list2]

In [11]:
#Make multi-dimensional array
my_array2 = np.array(multy_lists)

#Show array
my_array2

array([[ 10,  20,  30,  40],
       [100, 200, 300, 400]])

**Note:** You can work with a 2-D array like a matrix but is not a "matrix object".

In [14]:
#Lets get the size of the array
my_array2.shape

(2, 4)

In [15]:
#Find out the data type of the array
my_array2.dtype

dtype('int32')

### Special case of arrays

Zero:

In [16]:
#Making special case arrays

#Zeros
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Ones:

In [17]:
#Ones

np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Empty:

In [18]:
# An empty array

#np.empty(5)
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 4.94065646e-321],
       [1.11261570e-306, 8.90060779e-307, 1.86264515e-009]])

Identity:

In [19]:
# np.eye() eturn a 2-D array with ones on the diagonal and zeros elsewhere

x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### The .arange() method:

In [20]:
# Using the .arange() method you will get a 1-D array by default

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# start, stop and step

np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [22]:
# .arange() with specific range

np.arange(5, 50, 5).reshape(3,3)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
# Reshape the array 
my_array3 = np.arange(16).reshape(4,4)
my_array3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])