# Numpy

#### Documentation:

In [24]:
#For full documentation
website = "https://numpy.org/"
import webbrowser
webbrowser.open(website)

True

## Creatinng Arrays

In [2]:
# Creating Numpy arrays
import numpy as np

### 1-D Array from a list

In [3]:
# Converting from a list
#Lets start with a list

my_list1 = [10,20,30,40]

my_array1 = np.array(my_list1)

In [4]:
#Print out array

my_array1

array([10, 20, 30, 40])

In [5]:
# Check my object
type(my_array1)

numpy.ndarray

In [6]:
# Checking the type of the array
my_array1.dtype

dtype('int64')

Change the type of the objects

In [7]:
new_array1 = np.array([10, 20, 30, 40], dtype='float')

new_array1

array([10., 20., 30., 40.])

In [8]:
new_array1.dtype

dtype('float64')

### 2-D array from a list

In [9]:
# Make another list
my_list2 = [100,200,300,400]

#Make a list of lists
multy_lists = [my_list1, my_list2]

In [10]:
#Make multi-dimensional array
my_array2 = np.array(multy_lists)

#Show array
my_array2

array([[ 10,  20,  30,  40],
       [100, 200, 300, 400]])

**Note:** You can work with a 2-D array like a matrix but is not a "matrix object".

In [11]:
#Lets get the size of the array
my_array2.shape

(2, 4)

In [12]:
#Find out the data type of the array
my_array2.dtype

dtype('int64')

### The .arange() method:

#### 1-D array

In [22]:
# Using the .arange() method you will get a 1-D array by default

array_1d = np.arange(10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# start, stop and step

np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

#### 2-D array

In [23]:
# Using the reshape method

array_2d = np.arange(5, 50, 5).reshape(3,3)
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
# Another example...
np.arange(16).reshape(4,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 3-D array

In [25]:
array_3d = np.arange(24).reshape(2,3,4)
array_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### Linespace method

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

In [17]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [19]:
np.arange( 0, 3, 0.3 )                 # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [21]:
# We can chose how many numbers we want to set in a given range
np.linspace(0, 3, 10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

### Special cases arrays

**Zeros:** Creates an array full of zeros

In [16]:
#Making special case arrays

#Zeros
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Ones:** Creates an array full of ones

In [17]:
#Ones

np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Empty:** Creates an array whose initial content is random and depends on the state of the memory

In [18]:
# An empty array

#np.empty(5)
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 4.94065646e-321],
       [1.11261570e-306, 8.90060779e-307, 1.86264515e-009]])

**Eye:** Creates an array full of zeros wtih the diagonal full of ones

In [19]:
# np.eye() eturn a 2-D array with ones on the diagonal and zeros elsewhere
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Let's go to exercises!